# Generated by Django 4.2.20 on 2025-04-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_remove_job_users_and_more'),
        ('users', '0013_alter_user_managers_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
    ]
