# Generated by Django 4.2.21 on 2025-05-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
