# Generated by Django 4.2.21 on 2025-05-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_username_referral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
