# Generated by Django 4.2.21 on 2025-05-31 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_userdetails_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
