# Generated by Django 4.2.22 on 2025-06-09 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_performancereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancereview',
            old_name='recent_review',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='feedback_score',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='goals_completed',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='total_goals',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
