# Generated by Django 4.2.23 on 2025-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='stock_options',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
