# Generated by Django 4.2.23 on 2025-06-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_userdetails_bonus_userdetails_stock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
