# Generated by Django 5.1 on 2024-09-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/resumes/"
            ),
        ),
    ]
