# Generated by Django 5.1 on 2024-09-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_userdetails_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDetails",
        ),
    ]
