# Generated by Django 5.1 on 2024-11-13 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_posted_at'),
    ]

    operations = [
        # Commenting out the AddField operation since "created_at" already exists in the database.
        # migrations.AddField(
        #     model_name='job',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
    ]
