# Generated by Django 5.1 on 2025-04-08 16:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='base_pay_high',
        ),
        migrations.RemoveField(
            model_name='job',
            name='base_pay_low',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_hourly_pay',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_posted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateField(auto_now_add=True, default='2025-04-08'),
            preserve_default=False,
        ),
    ]
