# Generated by Django 4.2.21 on 2025-05-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_delete_registrationrequest_remove_job_base_pay_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjob',
            old_name='ended_at',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='userjob',
            name='started_at',
        ),
        migrations.AddField(
            model_name='userjob',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
