# Generated by Django 4.2.21 on 2025-05-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_onboardingtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnboardingTask',
        ),
    ]
