# Generated by Django 5.1 on 2024-09-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_jobapplication_resume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="applicants",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="user",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="email",
            field=models.EmailField(default="email@email.com", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="first_name",
            field=models.CharField(default="first", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="is_employee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="last_name",
            field=models.CharField(default="last", max_length=255),
            preserve_default=False,
        ),
    ]
