# Generated by Django 5.1 on 2024-11-13 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 21, 13, 49, 516602, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
