# Generated by Django 5.1 on 2025-04-09 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_registrationrequest_remove_job_posted_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='is_posted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(default='American Technology Initiative', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
