# Generated by Django merge command manually

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_created_at'),
        ('jobs', '0014_remove_registrationrequest_created_at_job_created_at_and_more'),
    ]

    operations = [
        # No operations are needed; this migration only exists to merge the two branches.
    ]
