# Generated by Django 4.2.20 on 2025-04-21 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0015_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='users',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='job',
            name='base_pay_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='base_pay_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_hourly_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='company',
            field=models.CharField(default='American Technology Initiative', max_length=255),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='pay',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
