# Generated by Django 4.2.23 on 2025-06-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_delete_onboardingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
