# Generated by Django 4.2.23 on 2025-06-26 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_jobapplication_admin_notes_jobapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescreeningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='prescreening/')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='assigned', max_length=50)),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='prescreening/submissions/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescreening_tasks', to='jobs.jobapplication')),
            ],
        ),
    ]
