# Generated by Django 4.2.23 on 2025-07-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_job_experience_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
