# Generated by Django 4.2.23 on 2025-08-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_jobapplication_current_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
