# Generated by Django 4.2.21 on 2025-05-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
